# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: send wtb news to discord server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:    
    - uses: actions/checkout@v4
      with:
        repository: M3tz3l/wtb-bot
        token: ${{ secrets.WTB_BOT_PAT }}
        path: ${{ github.workspace }}
        
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/wtb-bot-automation
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-
        
    - name: Install dependencies
      run: npm ci
        
    - name: Install Playwright Chromium (cached)
      run: npx playwright install chromium
        
    - name: Build and run
      run: |
        npm run build
        npm start
        
    - name: Update list of sent news
      working-directory: ./wtb-bot-automation
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "⏰ Github Action Cron" || exit 0
        git push
        
    env:
      TEST_MODE: 'false'
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      RESULTS_WEBHOOK_URL: ${{ secrets.RESULTS_WEBHOOK_URL }}
      SENT_NEWS_PATH: "${{ github.workspace }}/wtb-bot-automation/data/processed_news.json"
      SENT_RESULTS_PATH: "${{ github.workspace }}/wtb-bot-automation/data/processed_results.json"
