# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: send wtb news to discord server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:    
    - uses: actions/checkout@v2
      with:
        repository: M3tz3l/wtb-bot
        token: ${{ secrets.WTB_BOT_PAT }}
        path: ${{ github.workspace }}
        
    - uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/wtb-bot-automation
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Build and run
      run: |
        npm ci
        npm start
        
    - name: Update list of sent news
      working-directory: ./wtb-bot-automation
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "⏰ Github Action Cron" || exit 0
        git push
        
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      SENT_NEWS_PATH: "${{ github.workspace }}/wtb-bot-automation/data/processed_news.json"
